version: "2"
run:
  modules-download-mode: readonly
linters:
  default: none
  enable:
    - govet
    - ineffassign
    - misspell
    - unconvert
    - unused
    - staticcheck
    - modernize
    - testifylint
    - whitespace
  settings:
    staticcheck:
      checks:
        - all
        - -ST1000
        - -ST1003
        - -ST1016
    modernize:
      disable:
        - omitzero
        - newexpr
    testifylint:
      enable-all: true
      disable:
        - go-require
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
