apiVersion: v1
kind: Service
metadata:
  name: argo-rollouts-stable-service
  namespace: argo-rollouts
spec:
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: rollouts-demo