name: Gateway API plugin CI
on:
  # Run the workflow manually without pushing a commit
  workflow_dispatch:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"
env:
  GOLANG_VERSION: '1.24'

jobs:
  event_file:
    name: Event File
    runs-on: ubuntu-latest
    steps:
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: Event File
          path: ${{ github.event_path }}

  linting:
    name: Go code linting
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ env.GOLANG_VERSION }}

      - name: Checkout code
        uses: actions/checkout@v3.1.0

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v9
        with:
          args: --verbose --timeout 6m
          version: v2.11.4

  unit-tests:
    name: Unit tests running
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ env.GOLANG_VERSION }}

      - name: Checkout code
        uses: actions/checkout@v3.1.0

      - name: Unit tests running
        run: |
          make unit-tests

  e2e-tests:
    name: E2E tests 
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ env.GOLANG_VERSION }}
      - name: Install Chainsaw
        uses: kyverno/action-install-chainsaw@v0.1.0
        with:
          release: v0.2.14
      - name: Check install
        run: chainsaw version
      - name: Set up Kind
        uses: engineerd/setup-kind@v0.5.0
        with:
          version: "v0.23.0"
          skipClusterCreation: true

      - name: Checkout code
        uses: actions/checkout@v3.1.0

      - name: E2E tests
        run: |
          make e2e-tests

      - name: Upload E2E Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: E2E Test Results
          path: chainsaw-report.xml

  build:
    name: Build creation
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ env.GOLANG_VERSION }}

      - name: Checkout code
        uses: actions/checkout@v3.1.0

      - name: Build creation
        run: |
          go build -v
