# Runs in a separate workflow so that it has write permissions on PRs from forks.
# See https://github.com/EnricoMi/publish-unit-test-result-action#support-fork-repositories-and-dependabot-branches
name: Test Results

on:
  workflow_run:
    workflows: ["Gateway API plugin CI"]
    types:
      - completed

permissions: {}

jobs:
  publish-test-results:
    name: Publish Test Results
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion != 'skipped'
    permissions:
      checks: write
      pull-requests: write
      actions: read

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          run-id: ${{ github.event.workflow_run.id }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path: artifacts

      - name: Publish Chainsaw Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        with:
          check_name: Chainsaw E2E Test Results
          compare_to_earlier_commit: false
          fail_on: errors
          commit: ${{ github.event.workflow_run.head_sha }}
          event_file: artifacts/Event File/event.json
          event_name: ${{ github.event.workflow_run.event }}
          files: artifacts/Chainsaw Test Results/chainsaw-report.xml
